site_name: Wanderways
extra_css: [/assets/extra.css]
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.svg
  scheme: slate
  features:
    - content.code.copy
    - navigation.instant
    - navigation.tabs
plugins:
  - render_swagger
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav:
  - Introduction:
    - "index.md"
  - Project:
    - "project/index.md"
    - "project/roadmap.md"
    - "project/games.md"
    - "project/team.md"
  - Backend:
    - "backend/index.md"
    - Api:
      - Beforehand: "backend/routes/index.md"
      - Map: "backend/routes/map.md"
      - Game: "backend/routes/game.md"
      - Map Data: "backend/routes/mapdata.md"
      - Tag: "backend/routes/tag.md"
      - Statistics: "backend/routes/statistics.md"
    - Data harvest strategy : "backend/data-harvest-strategy.md"
    - Database: "backend/database.md"
  - Frontend:
    - "frontend/index.md"
    - "frontend/admin-panel.md"