openapi: 3.0.0
tags:
  - name: map
paths:
  /api/map/list/:
    get:
      summary: Get all the maps.
      description : Get the list of maps along with their description, thumbnails, tags, wiki link and statistiques such as popularity.
      tags:
        - map
      responses:
        "200":
          description: OK. More details on the page below.