openapi: 3.0.0
tags:
  - name: MapData
paths:
  /api/mapdata/{ID_MAP}/:
    get:
      summary: Get all the datas for a given map.
      tags:
        - MapData
      parameters:
        - in: path
          name: ID_MAP
          description: "The identifier of the map."
          required: true
          type: string
          example : "FRANCE_DEPARTMENTS"
# components: # schema is already visible as a typescript interface
#   schemas:
#     Map:
#       properties:
#         id:
#           type: string
#         data_translation:
#           type: array
#           items:
#             type: string
#         flag_url:
#           type: string
#         group:
#           type: object
#           properties:
#             id:
#               type: string
#             data_translation:
#               type: array
#               items:
#                 type: string
#             flag_url:
#               type: string
#             group:
#               type: nullable
#             numeric_code:
#               type: string
#         capital:
#           type: object
#           properties:
#             id:
#               type: string
#             data_translation:
#               type: array
#               items:
#                 type: string
#             flag_url:
#               type: string
#             group:
#               type: nullable
#             numeric_code:
#               type: string
#         numeric_code:
#           type: string