openapi: 3.0.0
tags:
  - name: Statistics
paths:
  /api/statistics/average-awareness/{ID_GAME_MODE}/{ID_MAP}:
    get:
      summary : 
      description : Get the list of maps along with their description, thumbnails, tags, wiki link and statistiques such as popularity.
      tags:
        - Statistics
      parameters:
        - in: path
          name: ID_GAME_MODE
          description: The gamemode's id
          required: true
          type: string
          example : "GAMEMODE_AGAINST-CLOCK"
        - in: path
          name: ID_MAP
          description: The map's id
          required: true
          type: string
          example : "FRANCE_DEPARTMENTS"
        - in: query
          name: ID_LANG
          description:  The language id. If not present, then takes all languages.
          required: false
          type: string
          example : "fr-FR"