openapi: 3.0.0
tags:
    - name: game
paths:
    /api/game/end:
        post:
            security:
                - sessionId: []
            summary: Ends a game session.
            tags:
                - game
            responses:
                '200':
                    description: OK
# defines cookie
components:
    securitySchemes:
        sessionId:
            type: string
            in: cookie
            name: SESSIONID
