openapi: 3.0.0
tags:
    - name: game
paths:
    /api/game/save-entry:
        post:
            security:
                - sessionId: []
            summary: Allows to send a result that the client computed as correct.
            tags:
                - game
            requestBody:
                description: A json object representing the player's answer.
                name: Player's answer
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                response:
                                    type: string
                                    summary: Player's answer
                                    example: 'loire atlantique'
                                supposedCorrespondance:
                                    type: string
                                    summary: The data's id supposedly associated, here 'FR-44'
                                    example: 'FR-44'
            responses:
                '200':
                    description: |
                        What the server concludes with the given answer.
                        |Enum|Value|
                        |-|-|
                        |OK|1|
                        |ALREADY_FOUND|2|
                        |WRONG_GUESS|3|
                        |UNKNOWN_ERROR|4|
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    reponsecode:
                                        type: number
                                        example: 1
# defines cookie
components:
    securitySchemes:
        sessionId:
            type: string
            in: cookie
            name: SESSIONID
