name: Deploy to online branch
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Git Version # Get the versin
        id: version
        uses: codacy/git-version@2.7.1
      - name: Use the version
        run: |
          echo ${{ steps.version.outputs.version }} | cut -c1-5
      - name: Use the previous version
        run: |
          echo ${{ steps.version.outputs.previous-version }}
      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: 3.x
      # - uses: actions/cache@v2
      #   with:
      #     key: ${{ github.ref }}
      #     path: .cache
      # - run: pip install mkdocs-material markdown Pygments mike mkdocs-render-swagger-plugin
      # - run: mike deploy --push --branch online --update-aliases ${{ steps.version.outputs.version }} latest
      